# Generated by Django 3.2 on 2021-05-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pics1')),
                ('decs', models.TextField()),
            ],
        ),
    ]
