# Generated by Django 3.2 on 2021-05-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_make'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='make',
            new_name='complete',
        ),
    ]
