# Generated by Django 3.2 on 2021-05-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_make_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complete',
        ),
    ]
